#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
readonly TARGET_HOST=pi@majanska-piramida.hopto.org
readonly TARGET_PATH=/home/pi/vhome_backend
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/server
readonly DATABASE_PATH=./init.sql
readonly COMPOSE_PATH=./docker-compose.yml

cargo build --release --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${COMPOSE_PATH} ${DATABASE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} sudo systemctl restart vhome.service
