//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod device;
pub mod groups_invitations;
pub mod sea_orm_active_enums;
pub mod task;
pub mod task_assign;
pub mod taskset;
pub mod thermometer;
pub mod tokens;
pub mod user_groups;
pub mod vgroup;
pub mod vuser;
