//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::device::Entity as Device;
pub use super::device_measurements::Entity as DeviceMeasurements;
pub use super::groups_invitations::Entity as GroupsInvitations;
pub use super::pairing_codes::Entity as PairingCodes;
pub use super::task::Entity as Task;
pub use super::task_assign::Entity as TaskAssign;
pub use super::taskset::Entity as Taskset;
pub use super::thermometer::Entity as Thermometer;
pub use super::tokens::Entity as Tokens;
pub use super::user_groups::Entity as UserGroups;
pub use super::vgroup::Entity as Vgroup;
pub use super::vuser::Entity as Vuser;
