//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use super::sea_orm_active_enums::RoleType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub vuser_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub vgroup_id: i32,
    pub role: RoleType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::vgroup::Entity",
        from = "Column::VgroupId",
        to = "super::vgroup::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Vgroup,
    #[sea_orm(
        belongs_to = "super::vuser::Entity",
        from = "Column::VuserId",
        to = "super::vuser::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Vuser,
}

impl Related<super::vgroup::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vgroup.def()
    }
}

impl Related<super::vuser::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vuser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
